### ISSUE TITLE
Prevent refresh until node is finished reloading or reload the page (insertBefore errors)

### ISSUE THREAD

**Issue by janat08** [janat08/makpal#14]
```
index.js:6896 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.insertBefore (http://localhost:3000/bundles/index.js:3391:16)
    at updateChildren (http://localhost:3000/bundles/index.js:3702:25)
    at patchVnode (http://localhost:3000/bundles/index.js:3747:21)
    at patch (http://localhost:3000/bundles/index.js:3777:13)
    at Fold.f (http://localhost:3000/bundles/index.js:705:40)
    at _try (http://localhost:3000/bundles/index.js:192:18)
    at Fold._n (http://localhost:3000/bundles/index.js:723:17)
    at Stream._n (http://localhost:3000/bundles/index.js:958:18)
    at MapOp._n (http://localhost:3000/bundles/index.js:805:11)
    at Stream._n (http://localhost:3000/bundles/index.js:958:18)
```

**Comment by janat08** [comment]
yes there is a section for this in docs, and it has the same API as webpack so that I can even use cycle-HMR package.

**Comment by janat08** [comment]
Tried, and failed. There's a brunch of this, the issue being that the doc prescribed method for cycle-hmr has changed since and may not even support the imperative API used in example like unicycle/cycle-for-all repos used as references.

**Comment by janat08** [comment]
cycle-restartable is apparently unstable/unrecommended, given that it strips attached methods such as select on graphql driver.
